# Generated by Django 5.2.10 on 2026-04-08 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_message_username_message_parent_message_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'permissions': [('can_moderate', 'Can moderate forum messages')]},
        ),
    ]
